## 벡터·행렬과 금융데이터 표현

### 1. 라이브러리 불러오기

In [1]:
import numpy as np
import pandas as pd

### 2. 스칼라와 벡터 만들기

In [2]:
# 스칼라: 하나의 숫자
stock_price = 70000
interest_rate = 0.035

print("삼성전자 주가:", stock_price)
print("기준금리:", interest_rate)

삼성전자 주가: 70000
기준금리: 0.035


In [3]:
# 벡터: 여러 숫자를 순서대로 저장
prices = np.array([70000, 71000, 69500, 72000])

print("주가 벡터:", prices)
print("벡터의 차원:", prices.ndim)
print("벡터의 원소 개수:", prices.shape[0])

주가 벡터: [70000 71000 69500 72000]
벡터의 차원: 1
벡터의 원소 개수: 4


In [ ]:
# 해석
# prices.ndim
# → 배열의 축 개수

# prices.shape
# → 각 축에 포함된 원소 개수

# prices는 원소가 4개인 1차원 배열입니다.
# 금융데이터 관점에서는 4개 날짜의 주가를 가진 벡터입니다.

### 3. 기업 재무정보를 벡터로 표현

In [4]:
# 부채비율, 유동비율, 영업이익률
company_a = np.array([180, 120, 8])

print("A기업 재무벡터:", company_a)
print("특성의 개수:", len(company_a))

A기업 재무벡터: [180 120   8]
특성의 개수: 3


In [ ]:
# 결과:

# A기업 재무벡터: [180 120   8]
# 특성의 개수: 3

# A기업은 3개의 재무변수로 표현되므로 3차원 특성벡터입니다.

### 4. 벡터의 크기 계산

In [5]:
v = np.array([3, 4])

vector_size = np.linalg.norm(v)

print("벡터:", v)
print("벡터의 크기:", vector_size)

벡터: [3 4]
벡터의 크기: 5.0


In [ ]:
# 계산 원리:

# 벡터의 크기
# = √(3² + 4²)
# = 5

### 5. 금융데이터 행렬 만들기

In [6]:
# 행: 기업
# 열: 부채비율, 유동비율, 영업이익률

financial_matrix = np.array([
    [180, 120,  8],
    [300,  70, -2],
    [100, 160, 12]
])

print("금융데이터 행렬:")
print(financial_matrix)

print("행렬 크기:", financial_matrix.shape)
print("행의 개수:", financial_matrix.shape[0])
print("열의 개수:", financial_matrix.shape[1])

금융데이터 행렬:
[[180 120   8]
 [300  70  -2]
 [100 160  12]]
행렬 크기: (3, 3)
행의 개수: 3
열의 개수: 3


In [ ]:
# 결과의 의미:

# 행렬 크기: (3, 3)

# 3개 기업 × 3개 재무변수

### 6. 전치행렬 확인

In [7]:
transpose_matrix = financial_matrix.T

print("원래 행렬:")
print(financial_matrix)

print("\n전치행렬:")
print(transpose_matrix)

원래 행렬:
[[180 120   8]
 [300  70  -2]
 [100 160  12]]

전치행렬:
[[180 300 100]
 [120  70 160]
 [  8  -2  12]]


In [ ]:
# 원래 행렬에서는 행이 기업이고 열이 변수입니다.
# 전치하면 다음과 같이 바뀝니다.
# 행: 재무변수
# 열: 기업

### 7. Pandas DataFrame으로 표현

In [8]:
df = pd.DataFrame(
    financial_matrix,
    index=["A기업", "B기업", "C기업"],
    columns=["부채비율", "유동비율", "영업이익률"]
)

df

,부채비율,유동비율,영업이익률
A기업,180,120,8
B기업,300,70,-2
C기업,100,160,12


In [10]:
# DataFrame 정보 확인
print("DataFrame 크기:", df.shape)
print("행 이름:", df.index.tolist())
print("열 이름:", df.columns.tolist())

DataFrame 크기: (3, 3)
행 이름: ['A기업', 'B기업', 'C기업']
열 이름: ['부채비율', '유동비율', '영업이익률']


### 8. DataFrame을 행렬로 변환

In [11]:
X = df.to_numpy()

print(X)
print(type(X))

[[180 120   8]
 [300  70  -2]
 [100 160  12]]
<class 'numpy.ndarray'>


In [ ]:
# 핵심 설명
# Pandas DataFrame
# → 변수명과 기업명이 포함된 분석용 표
# NumPy 배열
# → AI가 수학 계산에 활용하는 숫자 행렬

벡터 생성

→ 벡터 크기·차원 확인

→ 금융데이터 행렬 생성

→ 전치행렬

→ DataFrame을 NumPy 행렬로 변환

금융 포트폴리오 계산에 내적과 행렬곱 원리를  (꼭 기억 !!!!!)